server:
  port: 8085
  servlet:
    context-path: /szbapApi
spring:
  mvc:
    view:
      prefix: /WEB_INF/views/
      suffix: .jsp
  datasource:
    url: jdbc:mysql://localhost:3306/kzt?characterEncoding=UTF-8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver